repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black-jupyter
  - repo: https://github.com/kynan/nbstripout
    rev: "0.5.0"
    hooks:
      - id: nbstripout
  - repo: https://github.com/jazzband/pip-tools
    rev: "6.6.2"
    hooks:
      - id: pip-compile
